= Programmeren Basis - Deel PA4 - Oefeningen
Yanic Inghelbrecht
v2021.11.12.15.00
// toc and section numbering
:toc: preamble
:toclevels: 4
// geen auto section numbering voor oefeningen (handigere titels en toc)
//:sectnums:  
:sectlinks:
:sectnumlevels: 4
// source code formatting
:prewrap!:
:source-highlighter: rouge
:source-language: csharp
:rouge-style: github
:rouge-css: class
// inject css for highlights using docinfo
:docinfodir: ../common
:docinfo: shared-head
// folders
:imagesdir: images
:url-verdieping: ../{docname}-verdieping/{docname}-verdieping.adoc
:deel-pa2-oplossingen: ../deel-pa2-oplossingen/deel-pa2-oplossingen.adoc
// experimental voor kdb: en btn: macro's van AsciiDoctor
:experimental:

//preamble
[.text-right]
versie {revnumber}
 
 
== Oefening DPA4.metpersoonklasse

**Om deze oefening te kunnen oplossen moet je het stuk over klassen en properties al doorgenomen hebben.**



Herwerk link:{deel-pa2-oplossingen}#_oplossing_dpa2metmethods[de oplossing van DPA2.metmethods] zodat alle gegevens van één (fysieke) persoon in één (digitaal) persoon object wordt bijgehouden.

In plaats van de gegevens van een persoon losjes te verdelen over 6 parallelle arrays, bundelen we ze in `Persoon` objecten en houden al die objecten bij in één `Persoon[]` (i.e. een array van verwijzingen naar `Persoon` objecten). 

Je zult hiervoor dus een klasse `Persoon` moeten toevoegen en `Persoon` objecten gebruiken in het programma.

Je zult op meerdere plaatsen in de `Main` method aanpassingen moeten doen.

Je zult ook de `ToonPersoonDetails` method moeten aanpassen zodat die één `Persoon` parameter heeft i.p.v. allemaal aparte parameters voor de persoonsgegevens.

