= Programmeren Basis - Deel PA2 - Oplossingen
Yanic Inghelbrecht
v2021.10.28.13.00
:toc: preamble
:toclevels: 4
// geen auto section numbering voor oefeningen (handigere titels en toc)
//:sectnums: 
:sectlinks:
:sectnumlevels: 4
// source code formatting
:prewrap!:
:source-highlighter: rouge
:source-language: csharp
:rouge-style: github
:rouge-css: class
// inject css for highlights using docinfo
:docinfodir: ../common
:docinfo: shared-head
// folders
:imagesdir: images
:url-verdieping: ../{docname}-verdieping/{docname}-verdieping.adoc
// experimental voor kdb: en btn: macro's van AsciiDoctor
:experimental:

//preamble
[.text-right]
versie {revnumber}
 
== Oplossing DPA2.metmethods

De gevraagde methods werden toegevoegd en in de `Main` method werden deze methods consequent gebruikt. De `Main` code is dus heel wat eenvoudiger geworden!

[TIP]
====
Bij elke method die je moest schrijven waren er eigenlijk twee deelopdrachtjes : de code van de method schrijven en de code van de `Main` method aanpassen.

Als het bij een method niet lukt om de code van die method goed te krijgen, dan kun je toch nog proberen de tweede helft op te lossen :

. Kopieer de code van die ene method die niet lukte naar je eigen oplossing
. Probeer nu de `Main` method in je eigen oplossing aan te passen, zodat ze de gekopieerde method gebruikt.
====

.Program.cs :
[source,csharp,linenums]
----
public class Program {
	static void ToonTitel(string titel) {
		Console.WriteLine(titel);

		string lijntje = new string('-', titel.Length);
		Console.WriteLine(lijntje);
	}

	static string VraagStringAntwoord(string vraag) {
		string result;
		Console.Write($"{vraag} : ");
		result = Console.ReadLine().Trim();
		return result;
	}

	static string VraagNietLeegStringAntwoord(string vraag) {
		string result;
		do {
			result = VraagStringAntwoord(vraag);
		} while (result.Length == 0);
		return result;
	}

	// <1>
	static string VraagKeuzeMetCase(string vraag, string[] keuzes, bool isCaseInsensitive) {
		string result;
		string[] keuzesOmTeChecken;

		if (isCaseInsensitive) {
			keuzesOmTeChecken = new string[keuzes.Length];
			for (int i = 0; i < keuzes.Length; i++) {
				keuzesOmTeChecken[i] = keuzes[i].ToLower();
			}
		} else {
			keuzesOmTeChecken = keuzes;
		}

		int index;
		do {
			string keuzesTekst = string.Join('/', keuzes);
			Console.Write($"{vraag} ({keuzesTekst}) : ");

			string antwoord = Console.ReadLine().Trim();
			if (isCaseInsensitive) {
				antwoord = antwoord.ToLower();
			}

			index = Array.IndexOf(keuzesOmTeChecken, antwoord);
		} while (index == -1);
		result = keuzes[index];

		return result;
	}

	static string VraagKeuze(string vraag, string[] keuzes) {
		string result = VraagKeuzeMetCase(vraag, keuzes, true); // <2>
		return result;
	}

	static int VraagIntAntwoord(string vraag, int min, int max) {
		int result;
		bool isCorrectAntwoord;
		do {
			Console.Write($"{vraag} : ");
			string getalAlsTekst = Console.ReadLine().Trim();
			if (getalAlsTekst.Length > 0) {
				// gebruiker heeft iets ingetypt, is het een getal in [min, max]?
				bool isGeldig = int.TryParse(getalAlsTekst, out result);
				isCorrectAntwoord = isGeldig && (result >= min && result <= max);
			} else {
				// gebruiker heeft een lege string ingevoerd
				isCorrectAntwoord = true;
				result = int.MinValue; // we gebruiken deze waarde om aan te geven dat er niks werd ingevoerd
			}
		} while (!isCorrectAntwoord);

		return result;
	}

	static int VraagNietLeegIntAntwoord(string vraag, int min, int max) {
		int result;
		do {
			result = VraagIntAntwoord(vraag, min, max); // <3>
		} while (result == int.MinValue);

		return result;
	}

	static void ToonPersoonDetails(int index, string[] voornamen, string[] familienamen, bool[] isVrouwen, string[] postcodes, string[] gemeenten, int[] aantalKinderen) {
		Console.WriteLine("voornaam    : " + voornamen[index]);
		Console.WriteLine("familienaam : " + familienamen[index]);
		Console.WriteLine("geslacht    : " + (isVrouwen[index] ? "vrouw" : "man"));
		Console.WriteLine("postcode    : " + postcodes[index]);
		Console.WriteLine("gemeente    : " + gemeenten[index]);
		Console.WriteLine("kinderen    : " + aantalKinderen[index]);
	}

	public static void Main(string[] args) {
		string[] geslachtKeuzes = { "m", "v" };
		string[] geslachtLeegKeuzes = { "m", "v", "" };
		string[] jaNeeKeuzes = { "j", "n" };

		const int maxPersonen = 20;

		const int keuzeVoegToe = 1;
		const int keuzeVerwijder = 2;
		const int keuzeBewerk = 3;
		const int keuzeToon = 4;
		const int keuzeStop = 5;

		string[] voornamen = new string[maxPersonen];
		string[] familienamen = new string[maxPersonen];
		bool[] isVrouwen = new bool[maxPersonen];
		string[] postcodes = new string[maxPersonen];
		string[] gemeenten = new string[maxPersonen];
		int[] aantalKinderen = new int[maxPersonen];
		int aantalPersonen = 0;

		voornamen[aantalPersonen] = "Jan";
		familienamen[aantalPersonen] = "Janssens";
		isVrouwen[aantalPersonen] = false;
		postcodes[aantalPersonen] = "8501";
		gemeenten[aantalPersonen] = "Heule";
		aantalKinderen[aantalPersonen] = 2;
		aantalPersonen++;

		voornamen[aantalPersonen] = "Mieke";
		familienamen[aantalPersonen] = "Mickelsen";
		isVrouwen[aantalPersonen] = true;
		postcodes[aantalPersonen] = "9000";
		gemeenten[aantalPersonen] = "Gent";
		aantalKinderen[aantalPersonen] = 0;
		aantalPersonen++;

		int keuze = 0;
		do {
			Console.Clear();
			ToonTitel("Gekende personen");
			for (int i = 0; i < aantalPersonen; i++) {
				Console.WriteLine($"{i,2} {voornamen[i]} {familienamen[i]}, {gemeenten[i]}");
			}

			Console.WriteLine();
			ToonTitel("Hoofdmenu");
			Console.WriteLine("1) een persoon toevoegen");
			Console.WriteLine("2) een persoon verwijderen");
			Console.WriteLine("3) een persoon aanpassen");
			Console.WriteLine("4) alle details van een persoon zien");
			Console.WriteLine("5) stoppen");
			Console.WriteLine();

			keuze = VraagNietLeegIntAntwoord("Wat wil u doen", keuzeVoegToe, keuzeStop);
			Console.WriteLine();

			if (keuze == keuzeVoegToe) {
				ToonTitel("Persoon toevoegen");

				string antwoord;

				antwoord = VraagNietLeegStringAntwoord("Voornaam");
				voornamen[aantalPersonen] = antwoord;

				antwoord = VraagNietLeegStringAntwoord("Familienaam");
				familienamen[aantalPersonen] = antwoord;

				antwoord = VraagKeuze("Geslacht", geslachtKeuzes);
				isVrouwen[aantalPersonen] = (antwoord == "v");

				antwoord = VraagNietLeegStringAntwoord("Postcode");
				postcodes[aantalPersonen] = antwoord;

				antwoord = VraagNietLeegStringAntwoord("Gemeente");
				gemeenten[aantalPersonen] = antwoord;

				int aantal = VraagNietLeegIntAntwoord("Aantal kinderen", 0, int.MaxValue);
				aantalKinderen[aantalPersonen] = aantal;

				Console.WriteLine();
				ToonTitel("Ingevoerde gegevens");
				Console.WriteLine("voornaam    : " + voornamen[aantalPersonen]);
				Console.WriteLine("familienaam : " + familienamen[aantalPersonen]);
				Console.WriteLine("geslacht    : " + (isVrouwen[aantalPersonen] ? "vrouw" : "man"));
				Console.WriteLine("postcode    : " + postcodes[aantalPersonen]);
				Console.WriteLine("gemeente    : " + gemeenten[aantalPersonen]);
				Console.WriteLine("kinderen    : " + aantalKinderen[aantalPersonen]);

				antwoord = VraagKeuze("Wil u deze gegevens bewaren", jaNeeKeuzes);
				if (antwoord == "j") {
					aantalPersonen++;
				}

			} else if (keuze == keuzeVerwijder) {
				ToonTitel("Persoon verwijderen");

				int index = VraagNietLeegIntAntwoord("Welke persoon wil u verwijderen", 0, aantalPersonen - 1);

				ToonPersoonDetails(index, voornamen, familienamen, isVrouwen, postcodes, gemeenten, aantalKinderen);

				string antwoord = VraagKeuze("Wil u de gegevens van deze persoon daadwerkelijk verwijderen", jaNeeKeuzes);
				if (antwoord == "j") {
					// verwijder de persoon op positie 'index'
					for (int i = index; i < aantalPersonen - 1; i++) {
						voornamen[i] = voornamen[i + 1];
						familienamen[i] = familienamen[i + 1];
						isVrouwen[i] = isVrouwen[i + 1];
						postcodes[i] = postcodes[i + 1];
						gemeenten[i] = gemeenten[i + 1];
						aantalKinderen[i] = aantalKinderen[i + 1];
					}
					aantalPersonen--;
				}
			} else if (keuze == keuzeBewerk) {
				ToonTitel("Persoon bewerken");

				int index = VraagNietLeegIntAntwoord("Welke persoon wil u bewerken", 0, aantalPersonen - 1);
				Console.WriteLine("Indien u een gegeven ongewijzigd wil laten, druk dan gewoon op enter.");

				string voornaam = VraagStringAntwoord("Voornaam");

				string familienaam = VraagStringAntwoord("Familienaam");

				string geslacht = VraagKeuze("Geslacht", geslachtLeegKeuzes);

				string postcode = VraagStringAntwoord("Postcode");

				string gemeente = VraagStringAntwoord("Gemeente");

				int aantal = VraagIntAntwoord("Aantal kinderen", 0, int.MaxValue);

				Console.WriteLine();
				ToonTitel("Gewijzigde gegevens");
				if (voornaam != "") {
					Console.WriteLine("voornaam    : " + voornaam);
				}
				if (familienaam != "") {
					Console.WriteLine("familienaam : " + familienaam);
				}
				if (geslacht != "") {
					Console.WriteLine("geslacht    : " + (geslacht == "v" ? "vrouw" : "man"));
				}
				if (postcode != "") {
					Console.WriteLine("postcode    : " + postcode);
				}
				if (gemeente != "") {
					Console.WriteLine("gemeente    : " + gemeente);
				}
				if (aantal != int.MinValue) {
					Console.WriteLine("kinderen    : " + aantal);
				}

				string antwoord = VraagKeuze("Wil u deze wijziging(en) bewaren", jaNeeKeuzes);
				if (antwoord == "j") {
					if (voornaam != "") {
						voornamen[index] = voornaam;
					}
					if (familienaam != "") {
						familienamen[index] = familienaam;
					}
					if (geslacht != "") {
						isVrouwen[index] = (geslacht == "v");
					}
					if (postcode != "") {
						postcodes[index] = postcode;
					}
					if (gemeente != "") {
						gemeenten[index] = gemeente;
					}
					if (aantal != int.MinValue) {
						aantalKinderen[index] = aantal;
					}
				}
			} else if (keuze == keuzeToon) {
				int index = VraagNietLeegIntAntwoord("Van welke persoon wil u de details zien", 0, aantalPersonen - 1);

				ToonPersoonDetails(index, voornamen, familienamen, isVrouwen, postcodes, gemeenten, aantalKinderen);

				Console.WriteLine();
				Console.WriteLine("Druk op enter om terug te keren naar het hoofdmenu");
				Console.ReadLine();
			}

		} while (keuze != keuzeStop);

	}
}
----
<1> We tonen eens een `VraagKeuzeMetCase` variant waarbij de `bool` parameter aangeeft of de input al dan niet hoofdletterongevoelig moet zijn, gewoon omdat het een interessant stuk code is. Jullie oplossing hoeft deze variant natuurlijk niet te bevatten, dat stond niet in de opgave.
<2> De gevraagde method `VraagKeuze` kan dan gewoon deze variant oproepen met `true` als laatste parameter (want hoofdletter**on**gevoelig).
<3> We roepen `VraagIntAntwoord` op totdat we een waarde bekomen die niet op een leeg antwoord duidt.

