= Programmeren Basis - Deel 10 - Oefeningen
Frederiek De Wolf
v2022.11.24.15.00
include::../common/header-oefeningen.adoc[]


//preamble
[.text-right]
versie {revnumber}

include::../common/oefeningen-inleiding.adoc[]

//Y9.01 tem Y9.03 -> valt weg, verwerkt in uitleg
//Y9.04 -> opgenomen
//Y9.05 -> opgenomen
//Y9.06 -> opgenomen
//Y9.07 -> opgenomen
//Y9.08 -> opgenomen
//Y9.09 -> opgenomen
//Y9.10 -> opgenomen
//Y9.11 -> valt weg (dergelijk iets zit als voorbeeld in uitleg)
//Y9.12 -> opgenomen
//Y9.13 -> opgenomen

//10.01 - 10.09 -> niet opgenomen (bekijken of van toepassing in deel 11?)

//C41 -> valt weg, te basaal
//C42 -> valt weg, is met DateTime
//C43 -> opgenomen
//C44 -> opgenomen
//C45 -> valt weg, is met DateTime
//C46 -> valt weg (al een fahrenheit oefening bij de Y oefeningen)
//C47 - C53 -> niet opgenomen (bekijken of van toepassing in deel 11?)

//E27 -> niet opgenomen (bekijken of van toepassing in deel 11?)
//E28 -> niet opgenomen (bekijken of van toepassing in deel 11?)
//E29 - E32 -> vallen weg, oefening op method overloading
//E33 - E35 -> vallen weg, gelijkaardig Y oefeningen
//E36 -> niet opgenomen (bekijken of van toepassing in deel 11?)
  

== Vooraf

Voordien moest je de code van de oplossingen netjes tussen de accolades van de `Main` method plakken om een volledig en werkend programma te bekomen.

In de oefeningen hieronder worden meerdere methods gebruikt, die allen samen met de `Main` method in de `class Program` moeten terechtkomen.

De code in je __Visual Studio__ project zal er dus zo moeten uitzien :

[source, csharp, linenums]
----
using System;

namespace D10 {
    class Program {

		// Main method
		// ...
		
		// Extra method(s)
		// ...
	
	}
}
----

== Methods 

=== Oefening D10toonvierkant

//D1001

//Y9.04

Schrijf een `Main` method die een `ToonVierkant` method aanroept.  

Deze laatste print op het console scherm een vierkant van __5 op 5__ sterretjes (`*`).

[source,shell]
----
*****
*****
*****
*****
*****
----

== Methods met een parameter

=== Oefening D10toonvierkantparameters

//D1002

//Y9.05

Pas de method `ToonVierkant` aan zodat een parameter `zijde` wordt meegegeven die de afmetingen van het vierkant bepaalt.

== Methods met meerdere parameters

=== Oefening D10toonrechthoek
//D1003
//Y9.06

Schrijf een method `ToonRechthoek` met 2 parameters (`breedte` en `hoogte`) die een rechthoek van sterretjes op de console zet. 

Het programma vraagt de gebruiker om een `breedte` en een `hoogte`, en toont vervolgens een rechthoek van die afmeting. Indien de gebruiker geen keurige getallen invoert, blijft het programma de vraag herhalen.

Baseer je hierbij op de oplossing van oefening link:{deel-06-oefeningen}#_oefening_d06rechthoekopmaat[oefening D06rechthoekopmaat].


D06rechthoekopmaat.

[source,shell]
----
Geef de breedte: 10
Geef de hoogte: 3

**********
**********
**********
----


=== Oefening D10toonsomtussen
//D1004

//Y9.07

Schrijf een method `ToonSomTussen` met 2 parameters `min` en `max` die de som toont van alle getallen tussen `min` en `max` (grenzen inclusief).


=== Oefening D10printreeks
//D1005

[source,csharp,linenums]
----
static void Main() {
	PrintReeks(10, 15);
	PrintReeks(8, 3);
	PrintReeks(4, 4);
}

... // <1>
----
<1> Vul hier de ontbrekende method(s) aan.

De `PrintReeks` method gaat alle gehele getallen van het __kleinste__ naar het __grootste__ afdrukken, dit met een stap van __1__.

De uitvoer zou moeten opleveren...

[source,shell]
----
10 > 11 > 12 > 13 > 14 > 15
3 > 4 > 5 > 6 > 7 > 8
4
----

== Methods en arrays

=== Oefening D10toongetallenmetmethod
//D1006

//Y9.08

Schrijf een method `ToonGetallen` die een `int[]` als parameter heeft en de inhoud van deze array op de console zet. Dit is een variatie op link:{deel-09-oefeningen}#_oefening_d09toongetallenmetjoin[oefening D09toongetallenmetjoin].


Probeer dit uit met volgende code in de `Main` method...

[source,csharp,linenums]
----
int[] getallen = { 4, 7, 9, 34, 2, 56, 34, 78 };
ToonGetallen(getallen);
----

Het programma toont...

[source,shell]
----
4, 7, 9, 34, 2, 56, 34, 78
----

== Methods als query

=== Oefening D10vraaggebruikerompositiefgetal
//D1007

//Y9.09

Pas de oplossing van D10ToonRechthoek aan zodanig dat er een method `VraagGebruikerOmPositiefGetal` gebruikt wordt om de input af te handelen. 

Deze method heeft 1 parameter `vraag` en produceert een `int` waarde. 

De method stelt de meegegeven vraag, leest van de console en retourneert de ingegeven waarde.

Indien de gebruiker geen getal intypt (bijvoorbeeld __Hallo__) of een negatief getal ingeeft, zal de method de vraag herhalen totdat er een positief getal is ingevoerd.

Indien je gebruiker bijvoorbeeld __hallo__, __10__, __-1__ en __3__ invoert, ziet de uitvoer er zo uit...

[source,shell]
----
Geef de breedte : hallo
Geef de breedte : 10
Geef de hoogte : -1
Geef de hoogte : 3

**********
**********
**********
----

=== Oefening D10bevat
//D1008

//Y9.10

Schrijf een method `Bevat` met 2 parameters, een `string[] woorden` en een `string zoekwoord`.

De method retourneert `true` indien het zoekwoord in de array voorkomt en `false` indien dit niet het geval is.

[source,csharp,linenums]
----
string[] dieren = {"hond", "kat", "olifant", "krokodil"};

Console.WriteLine(Bevat(dieren, "papegaai")); // <1>
Console.WriteLine(Bevat(dieren, "olifant"));  // <2>
----
<1> drukt False af
<2> drukt True af

Herschrijf de oplossing van oefening D09zoekdier zodat deze `Bevat` method gebruikt wordt.


=== Oefening D10faculteit
//D1009

//Y9.12

Schrijf een programma dat de gebruiker om een getal vraagt en de faculteit van dat getal afbeeldt. 

De faculteit van een getal is het product van alle getalle van 1 t.e.m. dat getal. 

Men noteert dit wel eens met een uitroepteken.

Bijvoorbeeld bij invoer van __3__...

[source,shell]
----
Geef een getal : 3
3! is 6
----

Of bij invoer van __5__...

[source,shell]
----
Geef een getal : 5
5! is 120
----

Ter info : de faculteit van __3__ is __(1 * 2 * 3)__ en die van __5__ is __(1 * 2 * 3 * 4 * 5)__.

Voorzie in het programma een method `GetFaculteit` met een parameter van type `int` die een `int` waarde produceert.


=== Oefening D10intervaloverlap

Schrijf een method `IsOverlappend` die ons kan vertellen of twee intervallen overlappen.

Een interval is een verzameling getallen, bepaald door een ondergrens en een bovengrens en alle getallen daartussen.

Bijvoorbeeld het interval `[34,39]` bevat 34, 39 en alle getallen daartussen.

De method `IsOverlappend` heeft 4 parameters : twee grenzen van interval 1 en twee grenzen van interval 2. De return value geeft aan met `true/false` of de intervallen minstens 1 gemeenschappelijk getal hebben.

[source,csharp,linenums]
----
static bool IsOverlappend(int minInterval1, int maxInterval1, int minInterval2, int maxInterval2) { ... }
----

Je mag er hierbij van uitgaan dat geldt dat `minInterval1 \<= maxInterval1` en `minInterval2 \<= maxInterval2`.

Probeer je method uit met de volgende code en controleer of de output klopt :

[source,csharp,linenums]
----
Console.WriteLine( IsOverlappend(3, 6, 4, 10) ); // toont true
Console.WriteLine( IsOverlappend(4, 10, 3, 6) ); // toont true
Console.WriteLine( IsOverlappend(3, 6, 6, 10) ); // toont true
Console.WriteLine( IsOverlappend(6, 10, 3, 6) ); // toont true
Console.WriteLine( IsOverlappend(3, 6, 7, 10) ); // toont false
Console.WriteLine( IsOverlappend(7, 10, 3, 6) ); // toont false
Console.WriteLine( IsOverlappend(6, 6, 7, 7) );  // toont false
Console.WriteLine( IsOverlappend(7, 7, 6, 6) );  // toont false
Console.WriteLine( IsOverlappend(6, 6, 3, 10) ); // toont true
Console.WriteLine( IsOverlappend(3, 10, 6, 6) ); // toont true
Console.WriteLine( IsOverlappend(6, 6, 6, 10) ); // toont true
Console.WriteLine( IsOverlappend(6, 10, 6, 6) ); // toont true
----


=== Oefening D10temperatuur
//D1010

//Y9.13

Herschrijf oplossing D02temperatuur (__input Fahrenheit, output Celsius__) zodat een method `ConvertFahrenheitToCelsius` gebruikt wordt. 

Deze method heeft een parameter voor de temperatuur in __Fahrenheit__ en produceert de temperatuur in __Celsius__.


=== Oefening D10dagenfebruari
D1011

//C43

Maak zelf een method die antwoord op de vraag hoeveel dagen er in februari zijn van een bepaald jaar.

[source,csharp,linenums]
----
static void Main()
{
	do
	{
		Console.Write("Jaar?: ");
		int jaar = int.Parse(Console.ReadLine());
		Console.WriteLine($"In februari van {jaar} zijn er {...} dagen.");  // <1>
		Console.WriteLine();
	} while (true);
}

... // <2>

static bool IsSchrikkeljaar(int jaartal)
{
	return (jaartal % 400 == 0 || jaartal % 4 == 0 && jaartal % 100 != 0);
}
----
<1> Vervang de `...` door de nodige method call.
<2> Vervang de `...` door de nodige method definitie.

Bij invoer van __2016__ krijgen we...

[source,shell]
----
Jaar?: 2016 
In februari van 2016 zijn er 29 dagen.
----

Bij invoer van __2017__ krijgen we...

[source,shell]
----
Jaar?: 2017 
In februari van 2017 zijn er 28 dagen.
----

Bij invoer van __2100__ krijgen we...

[source,shell]
----
Jaar?: 2100 
In februari van 2100 zijn er 28 dagen.
----

=== Oefening D10dagen
//D1012

//C44

Breid nu het programma uit.  

Zorg ervoor dat de gebruiker ook zelf de maand kan uitkiezen.

Werk met een extra method, die voor eender welke maand zal opleveren hoeveel dagen deze heeft in een bepaald jaar.

[source,csharp,linenums]
----
static void Main()
{
	do
	{
		Console.Write("Maand?: ");
		int maand = int.Parse(Console.ReadLine());
		Console.Write("Jaar?: ");
		int jaar = int.Parse(Console.ReadLine());
		string[] maanden = {"januari", "februari", "maart", "april", "mei", "juni", "juli",
						"augustus", "september", "oktober", "november", "december"};
		Console.WriteLine($"In {maanden[maand - 1]} van {jaar} zijn er {...} dagen."); // <1>
		Console.WriteLine();
	} while (true);
}

... // <2>

static bool IsSchrikkeljaar(int jaartal)
{
	return (jaartal % 400 == 0 || jaartal % 4 == 0 && jaartal % 100 != 0);
}
----
<1> Vervang de `...` door de nodige method call.
<2> Vervang de `...` door de nodige method definitie.

Maak eventueel voor een stuk gebruik van je oplossing van voorgaande oefening.

Bij invoer van __4__ en __2017__ krijgen we...

[source,shell]
----
Maand?: 4
Jaar?: 2017
In april van 2017 zijn er 30 dagen.
----

Bij invoer van __2__ en __2017__ krijgen we...

[source,shell]
----
Maand?: 2
Jaar?: 2017
In februari van 2017 zijn er 28 dagen.
----

Bij invoer van __2__ en __2016__ krijgen we...

[source,shell]
----
Maand?: 2
Jaar?: 2016
In februari van 2016 zijn er 29 dagen.
----
