= Programmeren Basis - Deel 02 - Oefeningen
Yanic Inghelbrecht
v2022.10.11.14.00
include::../common/header-oefeningen.adoc[]


//preamble
[.text-right]
versie {revnumber}

include::../common/oefeningen-inleiding.adoc[]

 
== String concatenatie en input/output

 
=== {extra-icon} Oefening D02frietjes
// Y2.01
Schrijf een programma dat de gebruiker om 2 namen (bv. Jan en Mieke) alsook een gerecht (bv. frietjes) vraagt en vervolgens `Jan en Mieke eten graag frietjes.` op de console zet.

Een uitvoering van het programma ziet er zo uit :

[source,shell]
----
Geef een naam : Jan
Geef nog een naam : Mieke
Geef een gerecht : frietjes
Jan en Mieke eten graag frietjes.
----


=== Oefening D02leeftijd
// Y2.03
Schrijf een programma dat de gebruiker om zijn/haar naam (bv. Jan) en leeftijd (bv. 34) vraagt en volgende zinnetje op de console zet :

`Goeiedag Jan, je bent dus 34 jaar oud!`

Een uitvoering van het programma ziet er zo uit :

[source,shell]
----
Geef je naam : Jan
Geef je leeftijd : 34
Goeiedag Jan, je bent dus 34 jaar oud!
----


== Conversie
 
 
=== Oefening D02leeftijdvolgendjaar
// Y2.04
Schrijf een programma dat de gebruiker om zijn/haar naam (bv. Jan) en leeftijd (bv. 34), er een jaartje bijtelt en het volgende zinnetje toont :

`Oei oei Jan, volgend jaar ben je al 35 jaar oud!`

Een uitvoering van het programma ziet er zo uit :

[source,shell]
----
Geef je naam : Jan
Geef je leeftijd : 34
Oei oei Jan, volgend jaar ben je al 35 jaar oud!
----


=== Oefening D02som
// Y2.02
Schrijf een programma dat de gebruiker om 2 gehele getallen vraagt (bv. 5 en 6) en hun som op de console zet :

`5 plus 6 is 11.`


=== Oefening D02totalebedrag
// C03
Maak een programma dat de gebruiker vraagt hoeveel muntstukken van 2 en 1 euro hij heeft en vervolgens het totale bedrag toont. 

Een uitvoering ziet er zo uit :

[source,shell]
----
Aantal muntstukken van 2 euro : 4
Aantal muntstukken van 1 euro : 3
Het totale bedrag is 11 Euro.
----


=== Oefening D02gemiddelde
// Y2.05
Schrijf een programma dat de gebruiker om drie kommagetallen vraagt en hun gemiddelde toont.

			
=== Oefening D02temperatuur
// Y2.07
Schrijf een programma dat de gebruiker om een temperatuur in graden Fahrenheit (een kommagetal) vraagt en dan de corresponderende de temperatuur in graden Celsius (een kommagetal) toont.

De formule voor de omzetting van graden Fahrenheit (F) naar graden Celsius \(C)  is :
====
C = 5/9 * (F-32)
====

Tip : pas op met gehele delingen, i.e. delingen van gehele getallen!


=== {extra-icon} Oefening D02getalontleden
// Y2.10
Schrijf een programma dat de gebruiker om een geheel getal in [0,1000[ vraagt (dus van 0 t.e.m. 999) en vervolgens toont uit hoeveel honderdtallen, tientallen en eenheden dit bestaat. 

Tip : gebruik deling en modulo.

Een uitvoering met 123 als input ziet er zo uit :
[source,shell]
----
Geef een getal : 123
Het getal 123 bestaat uit
1 x 100
2 x  10
3 x   1
----


=== {extra-icon} Oefening D02hetmaandieet
Op de maan weegt alles (ongeveer) 6 keer minder dan op de aarde. Schrijf een programma dat de gebruiker om een gewicht in kilogram vraagt (een geheel getal) en dan op de console toont hoeveel het op de maan zou wegen (een kommagetal).

Een voorbeeld uitvoering :
[source,shell]
----
Geef je gewicht in kg : 83
Op de maan zou je ongeveer 13.833333333333334 kg wegen.
----


== Controlestructuren if en if/else


=== Oefening D02volwassen
// Y2.14
Schrijf een programma dat de gebruiker om zijn/haar leeftijd vraagt en toont `Je bent wel volwassen.` of `Je bent niet volwassen.`. Volwassen betekent 18 jaar of ouder. 

Gebruik in je code enkel de voorwaarde `leeftijd >= 18`.


=== Oefening D02gelijk
// Y2.15
Schrijf een programma dat de gebruiker om 2 gehele getallen vraagt en ofwel meldt `Ze zijn gelijk.` ofwel `Ze zijn verschillend.`.

		
=== Oefening D02quotient
// C05
Maak een programma dat de gebruiker om een deeltal en een deler vraagt en vervolgens het quotient op de console toont.

Indien de gebruiker voor de deler een nul invoert, is de deling niet toegelaten en wordt dit gemeld.

Een voorbeeld uitvoering :
[source,shell] 
----
Deeltal?: 10,6
Deler?: 5,1
Quotient: 2,07843137254902
----
Merk op dat je taalinstellingen er misschien voor zullen zorgen dat er `2.07843137254902` verschijnt (met een punt dus), dat is ook ok.

Een voorbeeld uitvoering met een nul als deler :
[source,shell]
----
Deeltal?: 10,6
Deler?: 0
Deling door nul wordt niet toegelaten.
----


=== Oefening D02even
// Y2.16
Schrijf een programma dat de gebruiker om een geheel getal vraagt en ofwel meldt of het getal even dan wel oneven is.

Tip : denk aan modulo 2!


=== {extra-icon} Oefening D02absolutewaarde
// Y2.17
Schrijf een programma dat de gebruiker om een getal vraagt en de absolute waarde van dit getal toont.

De absolute waarde 

- van een positief getal is het getal zelf
- van een negatief getal is het getal zonder minteken ervoor

Tip : Om het minteken weg te krijgen kun je bv. vermenigvuldigen met `-1`, want `-1 * (-10)` geeft `10`.