= Programmeren Basis - Deel PA3
Yanic Inghelbrecht
v2021.11.12.14.00
// toc and section numbering
:toc: preamble
:toclevels: 4
:sectnums: 
:sectlinks:
:sectnumlevels: 4
// source code formatting
:prewrap!:
:source-highlighter: rouge
:source-language: csharp
:rouge-style: github
:rouge-css: class
// inject css for highlights using docinfo
:docinfodir: ../common
:docinfo: shared-head
// folders
:imagesdir: images
:url-verdieping: ../{docname}-verdieping/{docname}-verdieping.adoc
// experimental voor kdb: en btn: macro's van AsciiDoctor
:experimental:

//preamble
[.text-right]
versie {revnumber}
 
== Personen applicatie met methods

In deze oefeningen gaan we de code van de personen applicatie uitbreiden zodat de gegevens in een bestand bewaard worden.

Het programma zal dus bij het opstarten een bestand met gegevens moeten inlezen. Bij het afsluiten van het programma moeten de gegevens bewaard worden in hetzelfde bestand.

In de oefeningen gaan we alleszins al methods moeten toevoegen voor het inladen en bewaren van de gegevens.

Vermits we de functionaliteit uitbreiden is dit GEEN refactoring : de gebruiker ziet immers dat er iets is veranderd aan het programma.