[NOTE]
======================================
We raden je aan om zoveel mogelijk oefeningen te maken, dat is de beste voorbereiding.

Als je te ver achterop raakt bij het volgen van deze cursus, dan zul je daar wellicht niet de tijd voor vinden want het zijn er behoorlijk veel.

* Indien je tijd tekort komt : concentreer je dan op de *__essentiële oefeningen__* (*zonder* {extra-icon}).

* Heb je wat tijd over : dan helpen de *__aanvullende oefeningen__* (*mét* {extra-icon}) om deze topics nog beter in de vingers te krijgen.
======================================

[WARNING]
======================================
Enkele aandachtspunten bij het oplossen van deze oefeningen :

* Volg de instructies in de oefeningen *nauwgezet*, je oplossing moet precies doen wat er gevraagd wordt. Als je oplossing slechts "min of meer, ongeveer" aan de opdracht voldoet ga je sommige problemen omzeilen i.p.v. ze op te lossen.

* Gebruik enkel de programmeertechnieken die tot op dit moment in de cursus aan bod kwamen. We zullen verderop in de cursus technieken tegenkomen die tot eenvoudigere oplossingen leiden, maar hier willen we dat je het oplost met de topics die we tot op dit punt in de cursus behandelden.

======================================
